### ISSUE TITLE
Aspsms\Exception

### ISSUE THREAD

**Issue by splattner** [nadar/aspsms#5]
Hi

I get the following Exception:

`
Aspsms\Exception Object ( [message:protected] => Error while printing the response code into sendStatus. ResponseCode seems not valid. Response: "StatusCode:8" [string:Exception:private] => [code:protected] => 0 [file:protected] => /Applications/MAMP/htdocs/myvbc/vendor/nadar/aspsms/src/Aspsms.php [line:protected] => 227 [trace:Exception:private] => Array ( [0] => Array ( [file] => /Applications/MAMP/htdocs/myvbc/libs/framework/helper.php [line] => 55 [function] => sendTextSms [class] => Aspsms\Aspsms [type] => -> [args] => Array ( [0] => XXX [1] => Array ( [0] => xxx xxx xx xx ) ) ) [1] => Array ( [file] => /Applications/MAMP/htdocs/myvbc/pages/auth.page.php [line] => 62 [function] => sendSMS [class] => MyHelper [type] => :: [args] => Array ( [0] => myVBC [1] => xxx xxx xx xx [2] => "XXX" ) ) [2] => Array ( [file] => /Applications/MAMP/htdocs/myvbc/libs/framework/page.php [line] => 231 [function] => createAccessAction [class] => PageAuth [type] => -> [args] => Array ( ) ) [3] => Array ( [file] => /Applications/MAMP/htdocs/myvbc/libs/framework/application.php [line] => 33 [function] => work [class] => MyPage [type] => -> [args] => Array ( ) ) [4] => Array ( [file] => /Applications/MAMP/htdocs/myvbc/index.php [line] => 125 [function] => run [class] => MyApplication [type] => :: [args] => Array ( ) ) ) [previous:Exception:private] => )
`

But Status Code 8 seems not valid

```
    /**
     * Response status codes when you send an sms
     *
     * @var array
     */
    private $sendStatusCodes = array(
        1 => "Ok",
        3 => "Authorization failed (wrong userkey and/or password).",
        5 => "Not enough Credits available.",
    );
```

What's wrong? Where do I find all possible status codes?

**Comment by nadar** [comment]
Hi @splattner 

I just added all status code descriptions, i collected them from:

https://webservice.aspsms.com/aspsmsx2.asmx?op=GetStatusCodeDescription

You can now download version 1.0.1. Let me know if your problem could be solved.

8 => `Invalid UserKey. Please check the spelling of the UserKey.`

**Comment by splattner** [comment]
perfect! Thx, indeed, the Userkey was the problem
